// <auto-generated />
namespace SAGA.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class alterTableRutasPerfil : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterTableRutasPerfil));
        
        string IMigrationMetadata.Id
        {
            get { return "201712111713152_alterTableRutasPerfil"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
